### PR TITLE
update test cases

### PR DESCRIPTION
**Pull request by tunnckoCore**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@jonschlinkert ping
hm.. interesting, I didnt remember this PR lol

**Comment by jonschlinkert** [comment]
yeah I haven't had a lot of time this week. starting to get a cold too

**Comment by jonschlinkert** [comment]
oh, thank you too :) I'll try to do this today if I can. No need to ping again though, it's on a list so I won't forget

**Comment by tunnckoCore** [comment]
@jonschlinkert merged with the latest master

more clear look of the PR can view here https://github.com/chorks/to-arg/commit/56daff0add5a40d0a0b2bb1f17d9c089d7df745d - just 4 new use cases

**Pull request merged**
